### ISSUE TITLE
[1.16.5] Vanished not exempt from required # to sleep

### ISSUE THREAD

**Issue by Exophobias** [RedstoneDubstep/Vanishmod#12]
Vanished players do not seem to be exempt from the required players to sleep before the time changes.

**Comment by RedstoneDubstep** [comment]
Hi, 
you are correct, this feature has not been implemented for 1.16.5 because I only support the two most recent major versions, and at the time of implementing the mentioned feature, 1.19 was already released so I had already stopped supporting 1.16.5.
