### ISSUE TITLE
Luckperms support

### ISSUE THREAD

**Issue by bigenergy** [RedstoneDubstep/Vanishmod#13]
I suggest you add support for luckperms for command /v
This will allow server administrators, for example, to control access to the team for moderators who do not have OP

**Comment by RedstoneDubstep** [comment]
Hello, thank you for your suggestion! I was under the impression that LuckPerms was only available for plugin loaders like Paper, but now that I know that there are also Forge versions available, I will try to add compatibility with that mod in the future.

**Comment by RedstoneDubstep** [comment]
So I've looked a little bit into how LuckPerms actually works, and from my testing, the suggested feature is already doable by setting the permissions `command.v` and `command.vanish` (or their subcommand versions), which seem to be automatically generated and managed by LuckPerms, to true for non-op users or moderators (I've tested this with Vanishmod v1.1.10 and LuckPerms 5.4.66). Is this what you were looking for, or did you want to suggest something else?

**Comment by RedstoneDubstep** [comment]
Closing this for now due to inactivity, if there are further questions feel free to reopen this issue

**Comment by SrRapero720** [comment]
hi
just to contribute to this
you won't need to use luckperms to allow "true/false" permissions, you can use ForgePermissions API

all you have to do is make your nodes and register them
![image](https://github.com/RedstoneDubstep/Vanishmod/assets/29090346/9c096e58-82dc-48c9-9a76-3ea31e1f6e5d)

![image](https://github.com/RedstoneDubstep/Vanishmod/assets/29090346/12c490ed-17de-4f63-90ce-17e9f4f37187)


Luckperms (for forge) retrieves the Forge Perm API, so you can use all nodes (modded included) on luckperms
Also, exists luckperms for forge

**Comment by SrRapero720** [comment]
anyway, luckperms also uses a new variant to check command permissions
`commands.vanish` node works :)
