### ISSUE TITLE
Leave and Join MSG

### ISSUE THREAD

**Issue by NmanBlast** [RedstoneDubstep/Vanishmod#15]
is there any way to disable that says "Player has disconnected" "Player has connected" the problem is that I am making a series of mods and I do not want to see the names of the "gods", I look forward to an early response.
Regards NmanBlast

**Comment by RedstoneDubstep** [comment]
Hello, the fake join/leave messages that get sent when vanishing/unvanishing can be disabled by setting the value of `sendFakeJoinLeaveMessages` in the Vanishmod config file to `false`.

**Comment by RedstoneDubstep** [comment]
Closing this issue because the question has been answered (or at least I think it has been). If there are further questions feel free to reopen it
