### ISSUE TITLE
[Suggestion] Add support for chat discord mod (Simple Discord Link (Bot)

### ISSUE THREAD

**Issue by Gbergz** [RedstoneDubstep/Vanishmod#17]
https://legacy.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot

Currently the chat is picking up players joining while being vanished.
If possible, add support so it doesn't send. (1.20.1 & 1.19.2)

Thanks :)

**Comment by RedstoneDubstep** [comment]
Hello, thank you for your suggestion! I looked a bit into the code of your suggested mod, and from what I've gathered there is no simple way to prevent messages from or mentioning specific (in this case vanished) players from being sent. As an example of what would be ideal for compatibility with Vanishmod, the discord relay mod mc2discord, which Vanishmod is compatible with (i.e. no messages of vanished players are sent to Discord via mc2discord), has a Hidden Players List that is easily accessible/modifiable and controls whether messages from a specific player should be sent to Discord. Therefore, I suggest switching to that discord relay mod if the join message appearing for vanished players is a significant issue for you. I will leave this issue open in case sdlink adds a system in the future that I can use to prevent specific players' messages from being sent to Discord.

**Comment by Gbergz** [comment]
Ah, I actually use Mc2Discord but in 1.19.2, wasn't updated when I checked last for 1.20.1. Probably will switch and use that then.

Thanks for the reply!

**Comment by hypherionmc** [comment]
We have official support for vanish in all our 3+ releases, so no need to add support from your side :smile:

**Comment by RedstoneDubstep** [comment]
Ah alright, that's awesome to hear! I'll close this issue then. Of course, if you want to suggest something to be added to this mod's API that would be beneficial to you, feel free to open another issue.
