### ISSUE TITLE
config file not found ?

### ISSUE THREAD

**Issue by Hypario** [RedstoneDubstep/Vanishmod#18]
Hello ! 

I am trying to use this mod on my server.
I encounter an issue with configuring the mod, basically, I can't find the config file in the config folder (apparently, it's not getting generated ??).

There is one that is generated in the serverconfig folder of the world folder, so I tried to copy and paste it to my config folder but with no success.

I am using Minecraft 1.19.2

**Comment by RedstoneDubstep** [comment]
Hello, the config file generated in the `serverconfig` folder is already in the correct location and does not need to be moved. Editing the config values in this file should have an effect ingame.
Edit: Please also make sure that the server is not running when changing something in the config file.

**Comment by Hypario** [comment]
Hello ! I tried modifying it in the serverconfig, but I had the same behavior, the config wasn't taken into account, I will try again later tonight (as I am not available) and edit this post with the result

Edit : the file was finally taken into account, sorry and thanks for the help !
note to myself : edit the config file in the serverconfig folder of the world folder
