### ISSUE TITLE
Vanished players appear in death messages and join/leave server messages [Forge 40.2.9] [Java 1.18.2]

### ISSUE THREAD

**Issue by Deathwolf01** [RedstoneDubstep/Vanishmod#19]
I have an issue where the vanished players still appear in chat messages if they die as well as joining/leaving the server. All non-op users can see these messages and it ruins some of the immersion we have on our server with certain vanished roles. We have about 20 people active and all are able to see the same messages of vanished players. I am not sure if I am missing a line in my vanishmod-server.toml file or if this is a bug with 1.18.2 that might need a mod update. Any solution would be greatly appreciated, thank you!

Java: 1.18.2
Forge Build: 40.2.9
VanishMod File on Server: Vanishmod-1.18.2-1.1.12.jar
serverconfig > vanishmod-server.toml file: https://pastebin.com/PhrdXyXY

Vanished Status on 2 player accounts:
Player 1 (QNPC17): OP User Level 4, Vanished enabled, Creative Gamemode
Player 2: Non-OP User, Not Vanished, Survival Gamemode

Issue: Player 2 who is not OP or vanished can see Player 1 (QNPC17) leave and join the server as well as death messages.
![image](https://github.com/RedstoneDubstep/Vanishmod/assets/39776756/98ff227e-76d0-4ae2-af6c-78ce6477ce75)

Attempted steps to resolve the issue taken:
1. I've set the vanishmod-server.toml file with fixModCompatibility = true
and rebooted the server and client instances but no luck in fixing the issue
2. I've tried changing the Forge build on both Server and Client to 40.2.10 and 40.2.4, but no luck same issue.

**Comment by RedstoneDubstep** [comment]
Hello, thank you for your detailed bug report! This definitely sounds like an issue in the mod, however with the supplied config file  and Forge version I cannot reproduce it. Are you using any additional mods on the server other than Vanishmod?

**Comment by Deathwolf01** [comment]
Thanks for the quick response! It could be an issue with another mod. We use a lot of mods for our server, but I did my best adding and configuring compatible mods together. Below is a list of all the mods used. Let me know if you need me to check anything else. Thanks

Full Server Mod List: https://pastebin.com/06aaYw6Y

Full Client Mod List: https://pastebin.com/NDF2rzG0

**Comment by RedstoneDubstep** [comment]
Hello, I was able to reproduce this issue with the installed mods and pinpoint the join/leave message issue to the mod "Custom Join & Leave Messages" (no idea regarding the Death Message yet though). I will try to fix the issue, expect a mod update in a couple of days, in the meantime you can fix at least part of the issue by removing the aforementioned mod.

**Comment by Deathwolf01** [comment]
That's awesome! And interesting, I'll give it some testing on a clone backup server I have. But a fix would still be appreciated to keep our current settings. Thank you for the quick support!
