### ISSUE TITLE
Leave/Join messages NOT disabling 1.19.2

### ISSUE THREAD

**Issue by vonist** [RedstoneDubstep/Vanishmod#20]
Hi, I'm having an issue where vanished players' fake join/leave messages will not be hidden. This is frustrating for the immersion to be broken, as we're trying to scare our members. 

Here's my server's config for the vanish mod: https: [//pastebin.com/qWDw9KQP](url)
However, I have tried setting sendFakeJoinLeaveMessages to FALSE, but for some reason once i restart the server it swaps back to true and I can't figure out what is causing it.

Here's my mod list:  [https://pastebin.com/6vJbznxP](url)

Please help us out, I did previously have the custom join/leave messages mod but we deleted it.

**Comment by RedstoneDubstep** [comment]
Hello,
the configuration resetting when the server restarts is a common (and really annoying) error of Forge servers. You need to edit the configuration while the server is offline, only then will it get properly applied. Please try setting the `sendFakeJoinLeaveMessages` to false while the server is offline and report back whether that worked.

**Comment by RedstoneDubstep** [comment]
I'm going to close this issue since there have been no further questions. If you have any other issue, feel free to reopen and reply to this issue.
