### ISSUE TITLE
no config file

### ISSUE THREAD

**Issue by PauPV3** [RedstoneDubstep/Vanishmod#27]
i don't have the config file

**Comment by RedstoneDubstep** [comment]
Hello, depending on what Minecraft version you use, finding server config files can be a bit tricky. Try searching both the `config` folder (at the same location where the `mods` folder is) and the `serverconfig` folder inside the `world` folder (and that `world` folder is again at the same location than the `mods` folder).
I'd appreciate if you tell me whether you've now found the config file, so I can close this issue.

**Comment by PauPV3** [comment]
found! It was at the server config inside the world wolder thanks you!
