### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by eConnah** [RedstoneDubstep/Vanishmod#3]
When installed on the client the noise suppression code causes the game to crash if punching an mob.
On multiplayer server.
Not vanished.

**Comment by eConnah** [comment]
newest forge version btw.

**Comment by RedstoneDubstep** [comment]
Hi, sorry for not responding for the last 20 days, I didn't get a proper notification for the issue.
You shouldn't by any means install this mod on the client, it only needs to be installed on the server to work.
