### ISSUE TITLE
NullPointerException. A TickingEntity crash of server.

### ISSUE THREAD

**Issue by GLMaster19** [RedstoneDubstep/Vanishmod#33]
Hello to all!
Have a problem that was already discussed here - a NullPointerException.
As I can see and understand, the problem is because of sounds from mods or something like this.
There is a crash report:
[crash-2024-08-02_16.41.45-server.txt](https://github.com/user-attachments/files/16473138/crash-2024-08-02_16.41.45-server.txt)

**Comment by RedstoneDubstep** [comment]
Hello, thanks for reporting! Gonna release a fix version in a bit
